# Generated by Django 3.2 on 2021-05-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementmodel',
            name='arm_hole_length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='measurementmodel',
            name='blouse_length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='measurementmodel',
            name='bust_length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='measurementmodel',
            name='lower_bust_length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='measurementmodel',
            name='neck_back_length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='measurementmodel',
            name='neck_front_length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='measurementmodel',
            name='shoulder_length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='measurementmodel',
            name='sleeve_length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='measurementmodel',
            name='sleeve_width_length',
            field=models.IntegerField(),
        ),
    ]
