# Generated by Django 3.2 on 2021-05-18 17:22

from django.db import migrations, models
import django.db.models.deletion
import orders.p_models.image_model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, max_length=254, null=True, upload_to=orders.p_models.image_model.uploadFolder)),
                ('source', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('size', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'images',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MeasurementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('blouse_opening', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('blouse_length', models.IntegerField(max_length=120)),
                ('arm_hole_length', models.IntegerField(max_length=120)),
                ('lower_bust_length', models.IntegerField(max_length=120)),
                ('bust_length', models.IntegerField(max_length=120)),
                ('shoulder_length', models.IntegerField(max_length=120)),
                ('neck_front_length', models.IntegerField(max_length=120)),
                ('neck_back_length', models.IntegerField(max_length=120)),
                ('sleeve_length', models.IntegerField(max_length=120)),
                ('sleeve_width_length', models.IntegerField(max_length=120)),
            ],
            options={
                'verbose_name': 'Measurement',
                'db_table': 'measurements',
            },
        ),
        migrations.CreateModel(
            name='SizeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('code', models.CharField(blank=True, default=None, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Size',
                'db_table': 'sizes',
            },
        ),
        migrations.CreateModel(
            name='StitchTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stitch_type', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('code', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('images', models.ManyToManyField(blank=True, default=None, to='orders.KImage')),
            ],
            options={
                'verbose_name': 'Stitch Type',
                'db_table': 'stitch_type',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_user', models.IntegerField(blank=True, default=None, null=True)),
                ('updated_user', models.IntegerField(blank=True, default=None, null=True)),
                ('stitch_type', models.CharField(default=None, max_length=80, null=True)),
                ('isClothAvailable', models.BooleanField(blank=True, default=False, null=True)),
                ('isStitchType', models.IntegerField(default=0)),
                ('expected_date', models.DateField()),
                ('extra_notes', models.CharField(blank=True, default=None, max_length=180, null=True)),
                ('user', models.IntegerField(blank=True, null=True)),
                ('clothSize', models.ManyToManyField(blank=True, null=True, to='orders.SizeModel')),
                ('images', models.ManyToManyField(blank=True, default=None, to='orders.KImage')),
                ('measurements', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.measurementmodel')),
            ],
            options={
                'db_table': 'orders',
                'managed': True,
            },
        ),
    ]
